# SPDX-License-Identifier: MPL-2.0
name: Basic Julia Test
on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26  # v3
      - uses: julia-actions/setup-julia@ac0d62164df5a47de404f4e96ce86a1a28a28d56  # v1
        with:
          version: '1.6'
      - run: |
          julia -e 'println("Julia version: ", VERSION)'
